#!/bin/bash

# this file should not be stored in the repository

export MESSENGER_TOKEN=EAAHSMr0RQqYBAHvLRPZAjoGVo9AAJSqdre4O72Ojp7Qvlsh1pDrcFtJZBnKQ4YYPFn1tqrFnxnaD6byOeEN4oA8OsJTAaJnM47BvJfYaqXcq6JynRowShLTa0cHHNgbao64SP6Qo0rKPRcRlXSsJfx4cjZAYxMIwszojgqmXgZDZD
node index.js
